name: Publish

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          bump_each_commit: true
      - name: Tag snapshot
        continue-on-error: true
        if: ${{ steps.version.outputs.version_type != 'none' }}
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: tagging-${{ steps.version.outputs.version_tag }}
      - name: 'change version'
        if: ${{ steps.version.outputs.version_type != 'none' }}
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.version.outputs.version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run build
      - uses: JS-DevTools/npm-publish@v3
        if: ${{ steps.version.outputs.version_type != 'none' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: ${{ github.ref_name == 'main' && 'latest' || 'next' }}
